### ISSUE TITLE
后续有无计划实现 对linux平台恶意文件检测？

### ISSUE THREAD

**Issue by cyber1c3** [PowerLZY/Bold-Falcon#11]
看了一眼你们的介绍，主要还是实现了对exe、dll、pdf、office、zip、jar、python等格式文件的分析，好像没看到对elf，so，ko等linux平台的检测功能，总得来说，目前你们偏win平台的沙箱检测

**Comment by PowerLZY** [comment]
您好，感谢您的关注！是的，我们目前还没有规划集成Linux，Android等其他系统文件的分析。如果您感兴趣可以关注cuckoo-linux，腾讯哈勃，CAPEv2等开源沙箱：
+ [HaboMalHunter](https://github.com/Tencent/HaboMalHunter#readme_cn) 
+ [腾讯哈勃Linux沙箱源码分析上](https://zhuanlan.zhihu.com/p/54756592)
+ [腾讯哈勃Linux沙箱源码分析下](https://zhuanlan.zhihu.com/p/54756845)
+ [CAPEv2](https://github.com/kevoreilly/CAPEv2)

**Comment by cyber1c3** [comment]
@PowerLZY 了解了，多谢，我最近也是想研究一波 linux沙箱的
